### ISSUE TITLE
Create OOP Partition Iterator tool

### ISSUE THREAD

**Issue by EllingOftedalKV** [kartverket/automatisk-generalisering#82]
Creating a Object Oriented Programming (OOP) tool which creates partitions and can iterate through the input features using the partitions and use a modular amount of custom logics on the inputs in each partition. 
```[tasklist]
### Design Logic
- [x] Create and test general logic for partition iteration using functional programming
```

```[tasklist]
### Create OOP version of Partition Iterator
- [ ] Make it possible to "extract" any output from custom logics used inside PartitionIterator
```

```[tasklist]
### Tasks
- [x] Crate a IO pram decorator to help the Partition Iterator to handle IO params from different logics
```
